knativeOperator:
  enabled: true
  priorityClassName: ""
  # Add any specific values for the Knative Operator chart here

# Overriding this value will allow to provide a custom knative-ingress-gateway configuration
knativeIngressGateway:
  spec:
    selector:
      istio: ingressgateway
    servers:
      - port:
          number: 80
          name: http
          protocol: HTTP
        hosts:
          - "*"

serving:
  enabled: true
  namespace: knative-serving
  manifest:
    spec:
      # The version of Knative Serving to install - you can upgrade one version at a time
      # See https://knative.dev/docs/install/operator/knative-with-operators/#install-knative-serving
      version: "v1.18.1"
      config:
        istio:
          external-gateways: |
            - name: knative-local-gateway
              namespace: knative-serving
              service: istio-ingressgateway.istio-system.svc.cluster.local

eventing:
  enabled: true
  namespace: knative-eventing
  manifest:
    spec:
      # The version of Knative Serving to install - you can upgrade one version at a time
      # See https://knative.dev/docs/install/operator/knative-with-operators/#installing-a-specific-version-of-eventing
      version: "v1.18.1"
